export const mockBitgoConstants = {
  ttl: 3600,
  constants: {
    maxFee: 100000000,
    maxFeeRate: 100000000000000000000,
    minFeeRate: 1100,
    minInstantFeeRate: -1000,
    fallbackFeeRate: 5000,
    minOutputSize: 2730,
    defaultGasPrice: 30000000000000,
    bitgoEthAddress: '0x0f47ea803926926f299b7f1afc8460888d850f47',
    enableSegwit: true,
    enableP2shP2wsh: true,
    enableP2wsh: false,
    tcelo: {
      tokens: [
        {
          type: 'tcusd',
          coin: 'tcelo',
          network: 'Alfajores',
          decimalPlaces: 18,
          name: 'tcusd',
          tokenContractAddress: '0x874069fa1eb16d44d622f2e0ca25eea172369bc1',
        },
      ],
    },
    tbsc: {
      tokens: [
        {
          type: 'tbsc:busd',
          coin: 'tbsc',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tbsc:busd',
          tokenContractAddress: '0xed24fc36d5ee211ea25a80239fb8c4cfd80f12ee',
        },
        {
          type: 'tbsc:usd1',
          coin: 'tbsc',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tbsc:usd1',
          tokenContractAddress: '0xb0652e70b4ad023d5be50a4427bfa556cf8cbb5e',
        },
        {
          type: 'tbsc:stgusd1',
          coin: 'tbsc',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tbsc:stgusd1',
          tokenContractAddress: '0xcad6876355c024b388de9a8c3b8172e7f86748ba',
        },
        {
          type: 'terc721:bsctoken',
          coin: 'tbsc',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'terc721:bsctoken',
          tokenContractAddress: '0xterc721:bsctoken',
          nftType: 'ERC721',
        },
        {
          type: 'terc1155:bsctoken',
          coin: 'tbsc',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'terc1155:bsctoken',
          tokenContractAddress: '0xterc1155:bsctoken',
          nftType: 'ERC721',
        },
      ],
    },
    teth: {
      tokens: [
        {
          type: 'terc',
          coin: 'teth',
          network: 'Kovan',
          tokenContractAddress: '0x945ac907cf021a6bcd07852bb3b8c087051706a9',
          decimalPlaces: 18,
          name: 'ERC Test Token',
        },
        {
          type: 'terc2dp',
          coin: 'teth',
          network: 'Kovan',
          tokenContractAddress: '0x107295c724c29553f51c5373b959f947065e6445',
          decimalPlaces: 2,
          name: 'ERC Test Token 2 Decimals',
        },
        {
          type: 'terc6dp',
          coin: 'teth',
          network: 'Kovan',
          tokenContractAddress: '0x4fcae60b370e5e523d18ba1fdf3bae46de88ac70',
          decimalPlaces: 6,
          name: 'ERC Test Token 6 Decimals',
        },
        {
          type: 'terc18dp',
          coin: 'teth',
          network: 'Kovan',
          tokenContractAddress: '0xd1e7cd06a5c81af9307cf3162f0fe740a0a69d25',
          decimalPlaces: 18,
          name: 'ERC Test Token 18 Decimals',
        },
        {
          type: 'test',
          coin: 'teth',
          network: 'Kovan',
          decimalPlaces: 18,
          name: 'test',
          tokenContractAddress: '0x1fb879581f31687b905653d4bbcbe3af507bed37',
        },
        {
          type: 'tbst',
          coin: 'teth',
          network: 'Kovan',
          decimalPlaces: 0,
          name: 'tbst',
          tokenContractAddress: '0xe5cdf77835ca2095881dd0803a77e844c87483cd',
        },
        {
          type: 'schz',
          coin: 'teth',
          network: 'Kovan',
          decimalPlaces: 18,
          name: 'schz',
          tokenContractAddress: '0x050e25a2630b2aee94546589fd39785254de112c',
          securityTokenType: 'harbor',
        },
        {
          type: 'tcat',
          coin: 'teth',
          network: 'Kovan',
          decimalPlaces: 18,
          name: 'tcat',
          tokenContractAddress: '0x63137319f3a14a985eb31547370e0e3bd39b03b8',
          securityTokenType: 'securrency',
        },
        {
          type: 'tfmf',
          coin: 'teth',
          network: 'Kovan',
          decimalPlaces: 18,
          name: 'tfmf',
          tokenContractAddress: '0xd8463d2f8c5b3be9de95c63b73a0ae4c79423452',
        },
        {
          type: 'tdai',
          coin: 'teth',
          network: 'Kovan',
          decimalPlaces: 18,
          name: 'tdai',
          tokenContractAddress: '0x4f96fe3b7a6cf9725f59d353f723c1bdb64ca6aa',
        },
      ],
    },
    gteth: {
      tokens: [
        {
          type: 'fixed',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'fixed',
          tokenContractAddress: '0xa13de8df4ef9d6016f0826858d48045848429390',
        },
        {
          type: 'gusdt',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'gusdt',
          tokenContractAddress: '0x64d081854fad45e64db52cd28ba78ae1ecfee59b',
        },
        {
          type: 'ghdo',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'ghdo',
          tokenContractAddress: '0x5426635915740813092eeff72158bc492799da5f',
        },
        {
          type: 'ghcn',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'ghcn',
          tokenContractAddress: '0xa05e3efe2771cd04191f3eadb9a99ba3b4bf9d26',
        },
        {
          type: 'gterc2dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 2,
          name: 'gterc2dp',
          tokenContractAddress: '0xe19e232e942cde4320b6354646cbb1336ae732c7',
        },
        {
          type: 'gterc6dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 6,
          name: 'gterc6dp',
          tokenContractAddress: '0xe7afa17e6e5257806d2309b01e6de320668ec3dc',
        },
        {
          type: 'gterc18dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'gterc18dp',
          tokenContractAddress: '0x61d54356be035944a3868eaa9556353b7150699d',
        },
        {
          type: 'gtaave18dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'gtaave18dp',
          tokenContractAddress: '0x631d5e3c45a459e8f98b9d6a2734fce7b051f845',
        },
        {
          type: 'gtbat18dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'gtbat18dp',
          tokenContractAddress: '0x95458b26c8b524eb5ef92c7a1759ede6224bef2e',
        },
        {
          type: 'gtcomp18dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'gtcomp18dp',
          tokenContractAddress: '0xa1ff97c394b25926acb09d12bacf0613055a2727',
        },
        {
          type: 'gtgrt18dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'gtgrt18dp',
          tokenContractAddress: '0x1441f298d1f15084a0e5c714c966033e39597de7',
        },
        {
          type: 'gtlink18dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'gtlink18dp',
          tokenContractAddress: '0xfe4537ff71aef28592c5c7331ed4b20f276d770b',
        },
        {
          type: 'gtmkr18dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'gtmkr18dp',
          tokenContractAddress: '0xf84e8207e4dc846e250208a6e4b05aa3e7ab00c6',
        },
        {
          type: 'gtsnx18dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'gtsnx18dp',
          tokenContractAddress: '0x50608a26bff103290a4a47b152395047801e9280',
        },
        {
          type: 'gtuni18dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'gtuni18dp',
          tokenContractAddress: '0x6be1a99c215872cea33217b0f4bad63f186ddfac',
        },
        {
          type: 'gtusdt6dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 6,
          name: 'gtusdt6dp',
          tokenContractAddress: '0x51445dcddf5246229bae8c0ba3ea462e63038641',
        },
        {
          type: 'gtyfi18dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'gtyfi18dp',
          tokenContractAddress: '0xf4755c1a9aaad9d6b919edb8346ce9b46d066be4',
        },
        {
          type: 'gtwbtc18dp',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 8,
          name: 'gtwbtc18dp',
          tokenContractAddress: '0xd4bccebe77b7c1da89818f8889e3ea09046e7e38',
        },
        {
          type: 'terc2dp1',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 2,
          name: 'terc2dp1',
          tokenContractAddress: '0xceef48d58cc3a51d8b6df155633007415b9bae01',
        },
        {
          type: 'terc2dp2',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 2,
          name: 'terc2dp2',
          tokenContractAddress: '0x168ae5b381f7c317ac6ef2161c6e5fcc0e0de41e',
        },
        {
          type: 'terc2dp3',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 2,
          name: 'terc2dp3',
          tokenContractAddress: '0x12cb9d6127ac74847cc444e6661cfd1b5107bd26',
        },
        {
          type: 'terc2dp4',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 2,
          name: 'terc2dp4',
          tokenContractAddress: '0x458fdef6e1e58614d82f3116d8ca1f23419cb8c0',
        },
        {
          type: 'terc2dp5',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 2,
          name: 'terc2dp5',
          tokenContractAddress: '0xf44c85bf1d556a8268a1212cf0b9248af4f238bd',
        },
        {
          type: 'terc6dp1',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 6,
          name: 'terc6dp1',
          tokenContractAddress: '0x3b9f958f0ba34aa103fabb054f29400703470bac',
        },
        {
          type: 'terc6dp2',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 6,
          name: 'terc6dp2',
          tokenContractAddress: '0x2508d109a0cd87e597a1de071325f5cf56d4639a',
        },
        {
          type: 'terc6dp3',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 6,
          name: 'terc6dp3',
          tokenContractAddress: '0xdda2375104ee9a97e1d7aa4bc48ede2c4c6ddf48',
        },
        {
          type: 'terc6dp4',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 6,
          name: 'terc6dp4',
          tokenContractAddress: '0x06c1f1195c59ec5f318d12d4cc2d1f9d45261756',
        },
        {
          type: 'terc6dp5',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 6,
          name: 'terc6dp5',
          tokenContractAddress: '0x3326af8eeb6d4ce1f1f0652fcb3d5e07cd9c1039',
        },
        {
          type: 'terc18dp1',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp1',
          tokenContractAddress: '0x9f77b76e6866b3f5dd99382c96f16eddabc0b78e',
        },
        {
          type: 'terc18dp2',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp2',
          tokenContractAddress: '0x18b17853ff62122c60f113b8b8967243c39ad30e',
        },
        {
          type: 'terc18dp3',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp3',
          tokenContractAddress: '0x96f13e2ea4b738380922dd9f5cd8fcf0416e5f2d',
        },
        {
          type: 'terc18dp4',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp4',
          tokenContractAddress: '0xbecf20f89b6898bd8bbf3fa93fb4bcda367b9594',
        },
        {
          type: 'terc18dp5',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp5',
          tokenContractAddress: '0x4464fe55f9a8aea46e02c4a22b4d74661805ec26',
        },
        {
          type: 'terc18dp6',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp6',
          tokenContractAddress: '0x998ddfd1ac3ed76fc163528c5fc69b8d67fa5395',
        },
        {
          type: 'terc18dp7',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp7',
          tokenContractAddress: '0xf2555ac243ab2606fa71e2f2728117054dd1867b',
        },
        {
          type: 'terc18dp8',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp8',
          tokenContractAddress: '0xd9da1e909e3b4b2c1ec31b702bef0bf1e42533e4',
        },
        {
          type: 'terc18dp9',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp9',
          tokenContractAddress: '0xb91be6a36b60c4576aff75a50d2b7c762349ddec',
        },
        {
          type: 'terc18dp10',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp10',
          tokenContractAddress: '0xc53d2c04795a1cef22a91c9d52c04f5082bb5631',
        },
        {
          type: 'terc18dp11',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp11',
          tokenContractAddress: '0xc325d7f188dc6015f45d3d39e58c5404e79b5cb9',
        },
        {
          type: 'terc18dp12',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp12',
          tokenContractAddress: '0x7a8f375798284920cd27d1c757ceca3675603ab1',
        },
        {
          type: 'terc18dp13',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp13',
          tokenContractAddress: '0x2e3f4bf47e4ea53a7a94f0597b47fe3caab78b0d',
        },
        {
          type: 'terc18dp14',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp14',
          tokenContractAddress: '0x4f369aa78b9f299cb50ad4d96e13bdfbd8be7239',
        },
        {
          type: 'terc18dp15',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'terc18dp15',
          tokenContractAddress: '0x0fcb9bc4c67d502a45a07f514638ca8f83ba2912',
        },
        {
          type: 'tusdc',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 6,
          name: 'tusdc',
          tokenContractAddress: '0x07865c6e87b9f70255377e024ace6630c1eaa37f',
        },
        {
          type: 'tusdt',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 6,
          name: 'tusdt',
          tokenContractAddress: '0xc2c527c0cacf457746bd31b2a698fe89de2b6d49',
        },
        {
          type: 'teuroc',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 6,
          name: 'teuroc',
          tokenContractAddress: '0xa683d909e996052955500ddc45ca13e25c76e286',
        },
        {
          type: 'tmatic',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 18,
          name: 'tmatic',
          tokenContractAddress: '0x499d11e0b6eac7c0593d8fb292dcbbf815fb29ae',
        },
        {
          type: 'terc721:bitgoerc721',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 0,
          name: 'terc721:bitgoerc721',
          tokenContractAddress: '0x8397b091514c1f7bebb9dea6ac267ea23b570605',
          nftType: 'ERC721',
        },
        {
          type: 'terc1155:bitgoerc1155',
          coin: 'gteth',
          network: 'Goerli',
          decimalPlaces: 0,
          name: 'terc1155:bitgoerc1155',
          tokenContractAddress: '0x87cd6a40640befdd96e563b788a6b1fb3e07a186',
          nftType: 'ERC1155',
        },
      ],
    },
    hteth: {
      tokens: [
        {
          type: 'tusds',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 6,
          name: 'tusds',
          tokenContractAddress: '0x399ae63d3fd23da82109fc8b632c19a1810f657e',
        },
        {
          type: 'tgousd',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 6,
          name: 'tgousd',
          tokenContractAddress: '0x51cef49e20d11a2735d09e3bb68d79ec490e3579',
        },
        {
          type: 'hteth:stgusd1',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 18,
          name: 'hteth:stgusd1',
          tokenContractAddress: '0x78f81399cd3bc0937ea9049cc6604fb6e67ebe83',
        },
        {
          type: 'hteth:tsteth',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 18,
          name: 'hteth:tsteth',
          tokenContractAddress: '0x3f1c547b21f65e10480de3ad8e19faac46c95034',
        },
        {
          type: 'hteth:gousd',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 6,
          name: 'hteth:gousd',
          tokenContractAddress: '0x65c959b9184b4f8c8633646d5dfd049d2ebc251a',
        },
        {
          type: 'hteth:usd1',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 18,
          name: 'hteth:usd1',
          tokenContractAddress: '0x978b411161325c7b689573396d717c828d9f480a',
        },
        {
          type: 'txsgd',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 6,
          name: 'txsgd',
          tokenContractAddress: '0x3f811bb6e605ef518b0cd9281eb4d9ad88a3953f',
        },
        {
          type: 'txusd',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 6,
          name: 'txusd',
          tokenContractAddress: '0x6d41906cce58491daf2ca8141a1c4b180fa6e7b9',
        },
        {
          type: 'tweth',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 18,
          name: 'tweth',
          tokenContractAddress: '0x94373a4919b3240d86ea41593d5eba789fef3848',
        },
        {
          type: 'hterc18dp',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 18,
          name: 'hterc18dp',
          tokenContractAddress: '0x7ca1945d697ac04965774700db8d0b64d81b288d',
        },
        {
          type: 'hteth:bgerchv2',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 18,
          name: 'hteth:bgerchv2',
          tokenContractAddress: '0xee4d03adfca9a902d09f6e3e09dbd5a8a5122fb6',
        },
        {
          type: 'hteth:aut',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 6,
          name: 'hteth:aut',
          tokenContractAddress: '0x63d0b467059a10b365aa18f441684ed154628f4e',
        },
        {
          type: 'hterc6dp',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 6,
          name: 'hterc6dp',
          tokenContractAddress: '0xdd415a799a11c2bcc380937b7c46d5035df4f1e2',
        },
        {
          type: 'hterc2dp',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 2,
          name: 'hterc2dp',
          tokenContractAddress: '0x5b494aba42b752b46c91e35fc914b4c2f8d61a00',
        },
        {
          type: 'trlusd',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 18,
          name: 'trlusd',
          tokenContractAddress: '0xe101fb315a64cda9944e570a7bffafe60b994b1d',
        },
        {
          type: 'teigen',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 18,
          name: 'teigen',
          tokenContractAddress: '0x3b78576f7d6837500ba3de27a60c7f594934027e',
        },
        {
          type: 'teinu',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 18,
          name: 'teinu',
          tokenContractAddress: '0xdeeeee2b48c121e6728ed95c860e296177849932',
        },
        {
          type: 'bgerch',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 18,
          name: 'bgerch',
          tokenContractAddress: '0xebe8b46a42f05072b723b00013ff822b2af1b5cb',
        },
        {
          type: 'terc721:token',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 0,
          name: 'terc721:token',
          tokenContractAddress: '0xterc721:token',
          nftType: 'ERC721',
        },
        {
          type: 'terc1155:token',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 0,
          name: 'terc1155:token',
          tokenContractAddress: '0xterc1155:token',
          nftType: 'ERC1155',
        },
        {
          type: 'tnonstandard:token',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 0,
          name: 'tnonstandard:token',
          tokenContractAddress: '0xtnonstandard:token',
          nftType: 'NONSTANDARD',
        },
        {
          type: 'terc721:bitgoerc721',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 0,
          name: 'terc721:bitgoerc721',
          tokenContractAddress: '0x8397b091514c1f7bebb9dea6ac267ea23b570605',
          nftType: 'ERC721',
        },
        {
          type: 'terc1155:bitgoerc1155',
          coin: 'hteth',
          network: 'Holesky',
          decimalPlaces: 0,
          name: 'terc1155:bitgoerc1155',
          tokenContractAddress: '0x87cd6a40640befdd96e563b788a6b1fb3e07a186',
          nftType: 'ERC721',
        },
      ],
    },
    txlm: {
      tokens: [
        {
          type: 'txlm:BST-GBQTIOS3XGHB7LVYGBKQVJGCZ3R4JL5E4CBSWJ5ALIJUHBKS6263644L',
          coin: 'txlm',
          network: 'Testnet',
          decimalPlaces: 7,
          name: 'BitGo Shield Token',
          domain: 'bitgo.com',
        },
        {
          type: 'txlm:TST-GBQTIOS3XGHB7LVYGBKQVJGCZ3R4JL5E4CBSWJ5ALIJUHBKS6263644L',
          coin: 'txlm',
          network: 'Testnet',
          decimalPlaces: 7,
          name: 'BitGo Test Token',
          domain: 'bitgo.com',
        },
      ],
    },
    teos: {
      tokens: [
        {
          type: 'teos:CHEX',
          coin: 'teos',
          network: 'Testnet',
          decimalPlaces: 8,
          tokenContractAddress: 'testtoken113',
          name: 'Chintai',
          symbol: 'CHEX',
        },
        {
          type: 'teos:IQ',
          coin: 'teos',
          network: 'Testnet',
          decimalPlaces: 3,
          tokenContractAddress: 'testtoken112',
          name: 'Everipedia',
          symbol: 'IQ',
        },
        {
          type: 'teos:BOX',
          coin: 'teos',
          network: 'Testnet',
          decimalPlaces: 6,
          tokenContractAddress: 'kvszn1xyz1bu',
          name: 'Box',
          symbol: 'BOX',
        },
        {
          type: 'teos:USDT',
          coin: 'teos',
          network: 'Testnet',
          decimalPlaces: 4,
          tokenContractAddress: 'lionteste212',
          name: 'Testnet EOS USDT',
          symbol: 'USDT',
        },
        {
          type: 'teos:VAULTA',
          coin: 'teos',
          network: 'Testnet',
          decimalPlaces: 4,
          tokenContractAddress: 'core.vaulta',
          name: 'Testnet Vaulta',
          symbol: 'A',
        },
      ],
    },
    talgo: {
      tokens: [
        {
          type: 'talgo:USDC-10458941',
          coin: 'talgo',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'USDC',
        },
        {
          type: 'talgo:USDt-180447',
          coin: 'talgo',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'Testnet Algorand USDT',
        },
        {
          type: 'talgo:USON-16026728',
          coin: 'talgo',
          network: 'Testnet',
          decimalPlaces: 2,
          name: 'Unison',
        },
        {
          type: 'talgo:SPRW-16026732',
          coin: 'talgo',
          network: 'Testnet',
          decimalPlaces: 4,
          name: 'Sparrow',
        },
        {
          type: 'talgo:KAL-16026733',
          coin: 'talgo',
          network: 'Testnet',
          decimalPlaces: 8,
          name: 'Kalki',
        },
        {
          type: 'talgo:JPT-162085446',
          coin: 'talgo',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'JPT',
        },
      ],
    },
    tavaxc: {
      tokens: [
        {
          type: 'tavaxc:link',
          coin: 'tavaxc',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tavaxc:link',
          tokenContractAddress: '0x0b9d5d9136855f6fec3c0993fee6e9ce8a297846',
        },
        {
          type: 'tavaxc:opm',
          coin: 'tavaxc',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tavaxc:opm',
          tokenContractAddress: '0x9a25414c8a41599cb7048f2e4dd42db02c1de487',
        },
        {
          type: 'tavaxc:cop2peq',
          coin: 'tavaxc',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tavaxc:cop2peq',
          tokenContractAddress: '0xbd3bd9b0c96be74e006333df6d1b5d9333ae1d43',
        },
        {
          type: 'tavaxc:xsgd',
          coin: 'tavaxc',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'tavaxc:xsgd',
          tokenContractAddress: '0xd769410dc8772695a7f55a304d2125320a65c2a5',
        },
        {
          type: 'tavaxc:bitgo',
          coin: 'tavaxc',
          network: 'Testnet',
          decimalPlaces: 8,
          name: 'tavaxc:bitgo',
          tokenContractAddress: '0x3ad5f9119ca063189095784b9a7d2bf80fc24de6',
        },
      ],
    },
    tsol: {
      tokens: [
        {
          type: 'tsol:srm',
          coin: 'tsol',
          network: 'Testnet',
          decimalPlaces: 9,
          name: 'Serum',
        },
        {
          type: 'tsol:usdc',
          coin: 'tsol',
          network: 'Testnet',
          decimalPlaces: 9,
          name: 'USD Coin',
        },
        {
          type: 'tsol:usdcv2',
          coin: 'tsol',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'USD Coin V2',
        },
        {
          type: 'tsol:ray',
          coin: 'tsol',
          network: 'Testnet',
          decimalPlaces: 9,
          name: 'Raydium',
        },
        {
          type: 'tsol:gmt',
          coin: 'tsol',
          network: 'Testnet',
          decimalPlaces: 9,
          name: 'GMT',
        },
        {
          type: 'tsol:usdt',
          coin: 'tsol',
          network: 'Testnet',
          decimalPlaces: 9,
          name: 'USD Tether',
        },
        {
          type: 'tsol:gari',
          coin: 'tsol',
          network: 'Testnet',
          decimalPlaces: 9,
          name: 'GARI',
        },
        {
          type: 'tsol:orca',
          coin: 'tsol',
          network: 'Testnet',
          decimalPlaces: 9,
          name: 'ORCA',
        },
        {
          type: 'tsol:slnd',
          coin: 'tsol',
          network: 'Testnet',
          decimalPlaces: 9,
          name: 'SOLEND',
        },
        {
          type: 'tsol:t22mint',
          coin: 'tsol',
          network: 'Testnet',
          decimalPlaces: 9,
          name: 'T22MINT',
        },
      ],
    },
    thbar: {
      tokens: [
        {
          type: 'thbar:usdc',
          coin: 'thbar',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'Testnet Hedera USD Coin',
        },
        {
          type: 'thbar:txsgd',
          coin: 'thbar',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'Testnet Fungible Token',
        },
      ],
    },
    tpolygon: {
      tokens: [
        {
          type: 'tpolygon:derc20',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tpolygon:derc20',
          tokenContractAddress: '0xfe4f5145f6e09952a5ba9e956ed0c25e3fa4c7f1',
        },
        {
          type: 'tpolygon:testcopm',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tpolygon:testcopm',
          tokenContractAddress: '0x866022aa0489bd84fd2b3e0320ba988d9385d439',
        },
        {
          type: 'tpolygon:link',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tpolygon:link',
          tokenContractAddress: '0x326c977e6efc84e512bb9c30f76e30c160ed06fb',
        },
        {
          type: 'tpolygon:opm',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tpolygon:opm',
          tokenContractAddress: '0xe71b2e809598d8398222b890d7203808fa1d631f',
        },
        {
          type: 'tpolygon:pme',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'tpolygon:pme',
          tokenContractAddress: '0x4659bc13c40a5012663b66102415262712303739',
        },
        {
          type: 'tpolygon:usdc',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'tpolygon:usdc',
          tokenContractAddress: '0x41e94eb019c0762f9bfcf9fb1e58725bfb0e7582',
        },
        {
          type: 'tpolygon:xsgd',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'tpolygon:xsgd',
          tokenContractAddress: '0xd769410dc8772695a7f55a304d2125320a65c2a5',
        },
        {
          type: 'tpolygon:usdt',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'tpolygon:usdt',
          tokenContractAddress: '0xbcf39d8616d15fd146dd5db4a86b4f244a9bc772',
        },
        {
          type: 'tpolygon:terc18dp',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tpolygon:terc18dp',
          tokenContractAddress: '0xa94c028c2e138b8ce20406e7e0d0b1e6180cb31f',
        },
        {
          type: 'tpolygon:terc10dp',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 10,
          name: 'tpolygon:terc10dp',
          tokenContractAddress: '0x58a3cd99e4955af8935fd68a4f5036d43fd155ea',
        },
        {
          type: 'tpolygon:terc6dp',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'tpolygon:terc6dp',
          tokenContractAddress: '0x46bada38d482c0973f45d307ebedd402be104e2d',
        },
        {
          type: 'tpolygon:BitGoTest',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tpolygon:BitGoTest',
          tokenContractAddress: '0xb99d708377a552ea5b7ffb14fa2cec9a21403d6f',
        },
        {
          type: 'tpolygon:name',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'tpolygon:name',
          tokenContractAddress: '0xba4bfed386dac111866aa2369319f2c2daf454af',
          nftType: 'ERC721',
        },
        {
          type: 'terc721:polygontoken',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'terc721:polygontoken',
          tokenContractAddress: '0xterc721:polygontoken',
          nftType: 'ERC721',
        },
        {
          type: 'terc1155:polygontoken',
          coin: 'tpolygon',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'terc1155:polygontoken',
          tokenContractAddress: '0xterc1155:polygontoken',
          nftType: 'ERC1155',
        },
      ],
    },
    tarbeth: {
      tokens: [
        {
          type: 'tarbeth:link',
          coin: 'tarbeth',
          network: 'ArbitrumSepolia',
          decimalPlaces: 18,
          name: 'tarbeth:link',
          tokenContractAddress: '0x143e1dae4f018ff86051a01d44a1b49b13704056',
        },
        {
          type: 'tarbeth:xsgd',
          coin: 'tarbeth',
          network: 'ArbitrumSepolia',
          decimalPlaces: 6,
          name: 'tarbeth:xsgd',
          tokenContractAddress: '0x63681558c1b680e43bbcadc0ced21075854bba87',
        },
      ],
    },
    topeth: {
      tokens: [
        {
          type: 'topeth:terc18dp',
          coin: 'topeth',
          network: 'OptimismSepolia',
          decimalPlaces: 18,
          name: 'topeth:terc18dp',
          tokenContractAddress: '0xe9df68a54bba438c8a6192e95f0f2c53ac93d997',
        },
        {
          type: 'topeth:wct',
          coin: 'topeth',
          network: 'OptimismSepolia',
          decimalPlaces: 18,
          name: 'topeth:wct',
          tokenContractAddress: '0x75bb6dca2cd6f9a0189c478bbb8f7ee2fef07c78',
        },
      ],
    },
    ttrx: {
      tokens: [
        {
          type: 'ttrx:wbtc',
          coin: 'ttrx',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'ttrx:wbtc',
          tokenContractAddress: 'TGkfUshdbAiNj5G1mynp2meq2BfF6XSGPf',
        },
        {
          type: 'ttrx:weth',
          coin: 'ttrx',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'ttrx:weth',
          tokenContractAddress: 'TCA8tecECSMwjg5jFz1J1V64k9ULZRSx7g',
        },
        {
          type: 'ttrx:usdc',
          coin: 'ttrx',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'ttrx:usdc',
          tokenContractAddress: 'TSdZwNqpHofzP6BsBKGQUWdBeJphLmF6id',
        },
        {
          type: 'ttrx:usdt',
          coin: 'ttrx',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'ttrx:usdt',
          tokenContractAddress: 'TG3XXyExBkPp9nzdajDZsozEu4BkaSJozs',
        },
        {
          type: 'ttrx:usd1',
          coin: 'ttrx',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'ttrx:usd1',
          tokenContractAddress: 'TMsuh7QxbJkYaLsGMGCgNJYtYjTZLJG3Np',
        },
        {
          type: 'ttrx:stgusd1',
          coin: 'ttrx',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'ttrx:stgusd1',
          tokenContractAddress: 'TPEwuCefwvzBcr9BHvg2xhJCaf499uGMZx',
        },
      ],
    },
    tsui: {
      tokens: [
        {
          type: 'tsui:deep',
          coin: 'tsui',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'tsui:deep',
          contractAddress:
            '0x36dbef866a1d62bf7328989a10fb2f07d769f4ee587c0de4a0a256e57e0a58a8::deep::DEEP',
        },
        {
          type: 'tsui:wal',
          coin: 'tsui',
          network: 'Testnet',
          decimalPlaces: 9,
          name: 'tsui:wal',
          contractAddress:
            '0x8190b041122eb492bf63cb464476bd68c6b7e570a4079645a8b28732b6197a82::wal::WAL',
        },
      ],
    },
    tbera: {
      tokens: [
        {
          type: 'tbera:bgt',
          coin: 'tbera',
          network: 'BeraCartio',
          decimalPlaces: 18,
          name: 'tbera:bgt',
          tokenContractAddress: '0xbda130737bdd9618301681329bf2e46a016ff9ad',
        },
        {
          type: 'tbera:honey',
          coin: 'tbera',
          network: 'BeraCartio',
          decimalPlaces: 18,
          name: 'tbera:honey',
          tokenContractAddress: '0x0e4aaf1351de4c0264c5c7056ef3777b41bd8e03',
        },
        {
          type: 'tbera:usdc',
          coin: 'tbera',
          network: 'BeraCartio',
          decimalPlaces: 18,
          name: 'tbera:usdc',
          tokenContractAddress: '0xd6d83af58a19cd14ef3cf6fe848c9a4d21e5727c',
        },
        {
          type: 'tbera:ibera',
          coin: 'tbera',
          network: 'BeraCartio',
          decimalPlaces: 18,
          name: 'tbera:ibera',
          tokenContractAddress: '0x5bdc3cae6fb270ef07579c428bb630e73c8d623b',
        },
      ],
    },
    txrp: {
      tokens: [
        {
          type: 'txrp:tst-rP9jPyP5kyvFRb6ZiRghAGw5u8SGAmU4bd',
          coin: 'txrp',
          network: 'Testnet',
          decimalPlaces: 15,
          name: 'txrp:tst-rP9jPyP5kyvFRb6ZiRghAGw5u8SGAmU4bd',
          issuerAddress: 'rP9jPyP5kyvFRb6ZiRghAGw5u8SGAmU4bd',
          currencyCode: 'TST',
          domain: 'xrpl.org',
        },
        {
          type: 'txrp:rlusd',
          coin: 'txrp',
          network: 'Testnet',
          decimalPlaces: 15,
          name: 'txrp:rlusd',
          issuerAddress: 'rQhWct2fv4Vc4KRjRgMrxa8xPN9Zx9iLKV',
          currencyCode: '524C555344000000000000000000000000000000',
          domain: 'ripple.com',
        },
        {
          type: 'txrp:xat',
          coin: 'txrp',
          network: 'Testnet',
          decimalPlaces: 15,
          name: 'txrp:xat',
          issuerAddress: 'rHy7UVhwM7Xgo4SoUTf5hE5yWKZKPEkxcL',
          currencyCode: '5841540000000000000000000000000000000000',
          domain: 'xat.com',
        },
        {
          type: 'txrp:xsgd',
          coin: 'txrp',
          network: 'Testnet',
          decimalPlaces: 15,
          name: 'txrp:xsgd',
          issuerAddress: 'rKgjEa9gEyyumaJsfkPq9uSAyaecQRmvYD',
          currencyCode: '5853474400000000000000000000000000000000',
          domain: 'straitsx.com',
        },
      ],
    },
    tapt: {
      tokens: [
        {
          type: 'tapt:usdt',
          coin: 'tapt',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'tapt:usdt',
          assetId: '0xd5d0d561493ea2b9410f67da804653ae44e793c2423707d4f11edb2e38192050',
        },
        {
          type: 'tapt:nftcollection1',
          coin: 'tapt',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'tapt:nftcollection1',
          nftCollectionId: '0xbbc561fbfa5d105efd8dfb06ae3e7e5be46331165b99d518f094c701e40603b5',
          nftType: 'Digital Asset',
        },
        {
          type: 'tapt:beta3loanbook',
          coin: 'tapt',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'tapt:beta3loanbook',
          nftCollectionId: '0x14d44152cb1050277338ab6c58416e074d4a34ddf431978b41b5a9d14f9884f2',
          nftType: 'Digital Asset',
        },
      ],
    },
    tstx: {
      tokens: [
        {
          type: 'tstx:tsbtc',
          coin: 'tstx',
          network: 'Testnet',
          decimalPlaces: 8,
          name: 'tstx:tsbtc',
          assetId: 'ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT.sbtc-token::sbtc-token',
        },
        {
          type: 'tstx:tsip6dp',
          coin: 'tstx',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'tstx:tsip6dp',
          assetId: 'STAG18E45W613FZ3H4ZMF6QHH426EXM5QTSAVWYH.tsip6dp-token::tsip6dp-token',
        },
        {
          type: 'tstx:tsip8dp',
          coin: 'tstx',
          network: 'Testnet',
          decimalPlaces: 8,
          name: 'tstx:tsip8dp',
          assetId:
            'STAG18E45W613FZ3H4ZMF6QHH426EXM5QTSAVWYH.tsip8dp-token-updated::tsip8dp-token-updated',
        },
      ],
    },
    tcoredao: {
      tokens: [
        {
          type: 'tcoredao:stcore',
          coin: 'tcoredao',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tcoredao:stcore',
          tokenContractAddress: '0x6401f24ef7c54032f4f54e67492928973ab87650',
        },
      ],
    },
    tsoneium: {
      tokens: [
        {
          type: 'terc721:soneiumtoken',
          coin: 'tsoneium',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'terc721:soneiumtoken',
          tokenContractAddress: '0xterc721:soneiumtoken',
          nftType: 'ERC721',
        },
        {
          type: 'terc1155:soneiumtoken',
          coin: 'tsoneium',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'terc1155:soneiumtoken',
          tokenContractAddress: '0xterc1155:soneiumtoken',
          nftType: 'ERC1155',
        },
        {
          type: 'tsoneium:test721',
          coin: 'tsoneium',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'tsoneium:test721',
          tokenContractAddress: '0xc78d4c49ccaa27a9ba9d0de9d93f50dbc67d4f8e',
          nftType: 'ERC721',
        },
        {
          type: 'tsoneium:test1155',
          coin: 'tsoneium',
          network: 'Testnet',
          decimalPlaces: 0,
          name: 'tsoneium:test1155',
          tokenContractAddress: '0xa8005b2990abfd688c0815b84509896f2c7bf78d',
          nftType: 'ERC1155',
        },
      ],
    },
    tnear: {
      tokens: [
        {
          type: 'tnear:tnep24dp',
          coin: 'tnear',
          network: 'Testnet',
          decimalPlaces: 24,
          name: 'tnear:tnep24dp',
          contractAddress: 'ft-tnep24dp.testnet',
          storageDepositAmount: '1250000000000000000000',
        },
        {
          type: 'tnear:usdc',
          coin: 'tnear',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'tnear:usdc',
          contractAddress: '3e2210e1184b45b64c8a434c0a7e7b23cc04ea7eb7a6c3c32520d03d4afcb8af',
          storageDepositAmount: '1250000000000000000000',
        },
      ],
    },
    tworld: {
      tokens: [
        {
          type: 'tworld:wld',
          coin: 'tworld',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tworld:wld',
          tokenContractAddress: '0x8803e47fd253915f9c860837f391aa71b3e03c5a',
        },
        {
          type: 'tworld:usdc',
          coin: 'tworld',
          network: 'Testnet',
          decimalPlaces: 6,
          name: 'tworld:usdc',
          tokenContractAddress: '0x66145f38cbac35ca6f1dfb4914df98f1614aea88',
        },
      ],
    },
    tvet: {
      tokens: [
        {
          type: 'tvet:vtho',
          coin: 'tvet',
          network: 'Testnet',
          decimalPlaces: 18,
          name: 'tvet:vtho',
          contractAddress: '0x0000000000000000000000000000456e65726779',
        },
      ],
    },
    underMaintenance: {},
    idfVersion: 1,
    enterpriseLicenses: {
      canAccessSettlement: ['bitgoOrg.settlement', 'canCreateOffchainWallet'],
      canAccessTrading: ['canCreateOffchainWallet', 'bitgoOrg.trading'],
      staking: ['bitgoOrg.staking'],
      stakingApi: ['bitgoOrg.stakingApi'],
      bitgoTrustAsKrs: ['bitgoOrg.isTrust'],
      canCreateOffchainWallet: ['bitgoOrg.tradingAccount'],
      bitgoNetwork: ['canCreateOffchainWallet'],
      marginTrading: ['canAccessTrading'],
      mtGox: ['canCreateOffchainWallet', 'canCreateCustodialWallet'],
      tradeAPI: ['canAccessTrading'],
      videoIdWaived: ['bitgoOrg.isTrust'],
      cheetahAccountId: ['bitgoOrg.isTrust'],
      escrow: ['bitgoOrg.escrow'],
      distributedCustodyWallet: ['bitgoOrg.distributedCustodyWallet'],
      selfCustodyLightningWallet: ['bitgoOrg.selfCustodyLightningWallet'],
      custodyLightningWallet: ['bitgoOrg.custodyLightningWallet'],
    },
    ofc: {
      tokens: [
        {
          backingCoin: 'tfiatusd',
          coin: 'ofc',
          decimalPlaces: 2,
          isFiat: true,
          name: 'Test USD',
          type: 'ofctusd',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tfiataed',
          coin: 'ofc',
          decimalPlaces: 2,
          isFiat: true,
          name: 'Testnet United Arab Emirates Dirham',
          type: 'ofctaed',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tfiateur',
          coin: 'ofc',
          decimalPlaces: 2,
          isFiat: true,
          name: 'Test Euro',
          type: 'ofcteur',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tbtc',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Test Bitcoin',
          type: 'ofctbtc',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tbtc4',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Testnet4 Bitcoin',
          type: 'ofctbtc4',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'teth',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test Ether',
          type: 'ofcteth',
          minimumDenomination: 1000000000000,
        },
        {
          backingCoin: 'hteth',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test Holesky Ether',
          type: 'ofchteth',
          minimumDenomination: 1000000000000,
        },
        {
          backingCoin: 'tavaxc',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test Avalanche C-Chain',
          type: 'ofctavaxc',
          minimumDenomination: 1000000000000,
        },
        {
          backingCoin: 'tstx',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Test Stacks',
          type: 'ofctstx',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tstx',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Test sBTC',
          type: 'ofctstx:tsbtc',
          addressCoin: 'tstx',
          minimumDenomination: 100000000,
        },
        {
          backingCoin: 'tcspr',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'Test Casper',
          type: 'ofctcspr',
          minimumDenomination: 1000000000,
        },
        {
          backingCoin: 'tnear',
          coin: 'ofc',
          decimalPlaces: 24,
          isFiat: false,
          name: 'Test Near',
          type: 'ofctnear',
          minimumDenomination: 1e24,
        },
        {
          backingCoin: 'tltc',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Test Litecoin',
          type: 'ofctltc',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tzec',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Test ZCash',
          type: 'ofctzec',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'txrp',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Test Ripple',
          type: 'ofctxrp',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'txrp:rlusd',
          coin: 'ofc',
          decimalPlaces: 15,
          isFiat: false,
          name: 'RLUSD',
          type: 'ofctxrp:rlusd',
          addressCoin: 'txrp',
          minimumDenomination: 1000000000000000,
        },
        {
          backingCoin: 'txrp:xsgd',
          coin: 'ofc',
          decimalPlaces: 15,
          isFiat: false,
          name: 'XSGB',
          type: 'ofctxrp:xsgd',
          addressCoin: 'txrp',
          minimumDenomination: 1000000000000000,
        },
        {
          backingCoin: 'txlm',
          coin: 'ofc',
          decimalPlaces: 7,
          isFiat: false,
          name: 'Test Stellar',
          type: 'ofctxlm',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tdash',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Test Dash',
          type: 'ofctdash',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tbch',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Test Bitcoin Cash',
          type: 'ofctbch',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'terc',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test ERC Token',
          type: 'ofcterc',
          addressCoin: 'teth',
          minimumDenomination: 1000000000000,
        },
        {
          backingCoin: 'terc18dp13',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test ERC Token 18 decimals',
          type: 'ofcterc18dp13',
          addressCoin: 'gteth',
          minimumDenomination: 1000000000000,
        },
        {
          backingCoin: 'terc18dp14',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test ERC Token 18 decimals',
          type: 'ofcterc18dp14',
          addressCoin: 'gteth',
          minimumDenomination: 1000000000000,
        },
        {
          backingCoin: 'terc18dp15',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test ERC Token 18 decimals',
          type: 'ofcterc18dp15',
          addressCoin: 'gteth',
          minimumDenomination: 1000000000000,
        },
        {
          backingCoin: 'test',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test Mintable ERC20 Token',
          type: 'ofctest',
          addressCoin: 'teth',
          minimumDenomination: 1000000000000,
        },
        {
          backingCoin: 'teos',
          coin: 'ofc',
          decimalPlaces: 4,
          isFiat: false,
          name: 'Test Eos',
          type: 'ofcteos',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'talgo',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Test Algorand',
          type: 'ofctalgo',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tetc',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test Ethereum Classic',
          type: 'ofctetc',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'thbar',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Testnet Hedera HBAR',
          type: 'ofcthbar',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tdoge',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Test Dogecoin',
          type: 'ofctdoge',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tada',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Test Cardano',
          type: 'ofctada',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tpolygon',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test Polygon (MATIC native)',
          type: 'ofctpolygon',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tbld',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Testnet Agoric',
          type: 'ofctbld',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'ttia',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Testnet Celestia',
          type: 'ofcttia',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tinjective',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet Injective',
          type: 'ofctinjective',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tosmo',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Testnet Osmosis',
          type: 'ofctosmo',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'thash',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'Testnet Provenance',
          type: 'ofcthash',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tsei',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Testnet Sei',
          type: 'ofctsei',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tzeta',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet Zeta',
          type: 'ofctzeta',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tatom',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Testnet Cosmos Hub ATOM',
          type: 'ofctatom',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tbsc',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet Binance Smart Chain',
          type: 'ofctbsc',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tsui',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'Testnet Sui',
          type: 'ofctsui',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'ttrx',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Testnet Tron',
          type: 'ofcttrx',
          minimumDenomination: 1000000000000,
        },
        {
          backingCoin: 'ttrx:usdt',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Tether USD',
          type: 'ofcttrx:usdt',
          addressCoin: 'ttrx',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'ttrx:usd1',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'USD1 Token',
          type: 'ofcttrx:usd1',
          addressCoin: 'ttrx',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'ttrx:stgusd1',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Staging USD1 Token',
          type: 'ofcttrx:stgusd1',
          addressCoin: 'ttrx',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tdot',
          coin: 'ofc',
          decimalPlaces: 12,
          isFiat: false,
          name: 'Test Polkadot',
          type: 'ofctdot',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'tsol',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'Test Solana',
          type: 'ofctsol',
          minimumDenomination: 1,
        },
        {
          backingCoin: 'hterc18dp',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test ERC Token 18 decimals',
          type: 'ofchterc18dp',
          addressCoin: 'hteth',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'hterc6dp',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Test ERC Token 6 decimals',
          type: 'ofchterc6dp',
          addressCoin: 'hteth',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tusds',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Holesky Testnet USD Standard',
          type: 'ofctusds',
          addressCoin: 'hteth',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'hteth:gousd',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Holesky Testnet GoUSD',
          type: 'ofchteth:gousd',
          addressCoin: 'hteth',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tgousd',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Holesky Testnet GoUSD',
          type: 'ofctgousd',
          addressCoin: 'hteth',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'hteth:usd1',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Holesky Testnet USD1',
          type: 'ofchteth:usd1',
          addressCoin: 'hteth',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'hteth:stgusd1',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Holesky Testnet USD1',
          type: 'ofchteth:stgusd1',
          addressCoin: 'hteth',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tbsc:usd1',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test USD1 Token',
          type: 'ofctbsc:usd1',
          addressCoin: 'tbsc',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tbsc:stgusd1',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test USD1 Token',
          type: 'ofctbsc:stgusd1',
          addressCoin: 'tbsc',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tarbeth',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet Arbitrum Ethereum (L2 Chain)',
          type: 'ofctarbeth',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tarbeth:link',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Arbitrum Test LINK',
          type: 'ofctarbeth:link',
          addressCoin: 'tarbeth',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tcoreum',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Test Coreum',
          type: 'ofctcoreum',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'ttao',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'Testnet Bittensor',
          type: 'ofcttao',
          minimumDenomination: 1000000000,
        },
        {
          backingCoin: 'tcelo',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet Celo Gold',
          type: 'ofctcelo',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'txtz',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Testnet Tezos',
          type: 'ofctxtz',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'avaxc:link',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Test Chainlink',
          type: 'ofctavaxc:link',
          addressCoin: 'tavaxc',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tsol:gari',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'testnet Gari Token',
          type: 'ofctsol:gari',
          addressCoin: 'tsol',
          minimumDenomination: 1000000000,
        },
        {
          backingCoin: 'topeth',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet Optimism Ethereum (L2 Chain)',
          type: 'ofctopeth',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tpolygon:link',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Polygon Test LINK',
          type: 'ofctpolygon:link',
          addressCoin: 'tpolygon',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tpolygon:usdc',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'USD Coin',
          type: 'ofctpolygon:usdc',
          addressCoin: 'tpolygon',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tpolygon:usdt',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Tether USD',
          type: 'ofctpolygon:usdt',
          addressCoin: 'tpolygon',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tpolygon:xsgd',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'XSGD',
          type: 'ofctpolygon:xsgd',
          addressCoin: 'tpolygon',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tsol:slnd',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'testnet SOLEND',
          type: 'ofctsol:slnd',
          addressCoin: 'tsol',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tsol:usdt',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'testnet USD Tether',
          type: 'ofctsol:usdt',
          addressCoin: 'tsol',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tsol:srm',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'testnet Serum',
          type: 'ofctsol:srm',
          addressCoin: 'tsol',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tsol:orca',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'testnet ORCA',
          type: 'ofctsol:orca',
          addressCoin: 'tsol',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tsol:usdc',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'testnet USD Coin',
          type: 'ofctsol:usdc',
          addressCoin: 'tsol',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tsol:ray',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'testnet Raydium',
          type: 'ofctsol:ray',
          addressCoin: 'tsol',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tsol:gmt',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'testnet GMT',
          type: 'ofctsol:gmt',
          addressCoin: 'tsol',
          minimumDenomination: 1000000000,
        },
        {
          backingCoin: 'tton',
          coin: 'ofc',
          decimalPlaces: 9,
          isFiat: false,
          name: 'Test Ton',
          type: 'ofctton',
          minimumDenomination: 1000000000,
        },
        {
          backingCoin: 'tcoredao',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet coredao chain',
          type: 'ofctcoredao',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tpolyx',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Testnet Polymesh',
          type: 'ofctpolyx',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tbera',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet Berachain',
          type: 'ofctbera',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'toas',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet oaschain',
          type: 'ofctoas',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tmon',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet Monad',
          type: 'ofctmon',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tstt',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet somnia',
          type: 'ofctstt',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tworld',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet world',
          type: 'ofctworld',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tsoneium',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet soneium',
          type: 'ofctsoneium',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tflr',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet flare',
          type: 'ofctflr',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tsgb',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet songbird',
          type: 'ofctsgb',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'txdc',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet XDC',
          type: 'ofctxdc',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'twemix',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet wemix',
          type: 'ofctwemix',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'tapt',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Testnet Aptos',
          type: 'ofctapt',
          minimumDenomination: 100000000,
        },
        {
          backingCoin: 'tbaby',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Testnet Babylon',
          type: 'ofctbaby',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tcronos',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Testnet Cronos POS',
          type: 'ofctcronos',
          minimumDenomination: 100000000,
        },
        {
          backingCoin: 'tinitia',
          coin: 'ofc',
          decimalPlaces: 6,
          isFiat: false,
          name: 'Testnet Initia',
          type: 'ofctinitia',
          minimumDenomination: 1000000,
        },
        {
          backingCoin: 'tasi',
          coin: 'ofc',
          decimalPlaces: 18,
          isFiat: false,
          name: 'Testnet Fetch Native',
          type: 'ofctasi',
          minimumDenomination: 1000000000000000000,
        },
        {
          backingCoin: 'ticp',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Testnet ICP',
          type: 'ofcticp',
          minimumDenomination: 100000000,
        },
        {
          backingCoin: 'tstx:tsbtc',
          coin: 'ofc',
          decimalPlaces: 8,
          isFiat: false,
          name: 'Test sBTC',
          type: 'ofctstx:tsbtc',
          addressCoin: 'tstx',
          minimumDenomination: 100000000,
        },
      ],
    },
    coins: [
      'tbtc',
      'tbtcsig',
      'tbtc4',
      'tbch',
      'tbsv',
      'tltc',
      'tdash',
      'tzec',
      'hteth',
      'txrp',
      'txlm',
      'talgo',
      'teos',
      'ttrx',
      'txtz',
      'tetc',
      'tavaxc',
      'tavaxp',
      'tcelo',
      'tbsc',
      'tcspr',
      'tstx',
      'thbar',
      'tsol',
      'tdot',
      'ofc',
      'tfiatusd',
      'tfiateur',
      'tfiatgbp',
      'tfiataed',
      'tfiatsgd',
      'tnear',
      'tpolygon',
      'tada',
      'tdoge',
      'tsui',
      'tatom',
      'tosmo',
      'thash',
      'ttia',
      'tsei',
      'tbld',
      'tinjective',
      'tzeta',
      'tton',
      'toas',
      'twemix',
      'tarbeth',
      'topeth',
      'tcoredao',
      'tflr',
      'tmon',
      'tsoneium',
      'tsgb',
      'tworld',
      'tthorchain:rune',
      'tapt',
      'ttao',
      'tbaby',
      'txdc',
      'tpolyx',
      'tcronos',
      'tasi',
      'tinitia',
      'tusds',
      'tgousd',
      'hteth:stgusd1',
      'hteth:tsteth',
      'hteth:gousd',
      'hteth:usd1',
      'txsgd',
      'txusd',
      'tweth',
      'hterc18dp',
      'hteth:bgerchv2',
      'hteth:aut',
      'hterc6dp',
      'hterc2dp',
      'trlusd',
      'teigen',
      'teinu',
      'bgerch',
      'terc721:token',
      'terc1155:token',
      'tnonstandard:token',
      'terc721:bitgoerc721',
      'terc1155:bitgoerc1155',
      'txlm:TST-GBQTIOS3XGHB7LVYGBKQVJGCZ3R4JL5E4CBSWJ5ALIJUHBKS6263644L',
      'tcusd',
      'tbsc:busd',
      'tbsc:usd1',
      'tbsc:stgusd1',
      'terc721:bsctoken',
      'terc1155:bsctoken',
      'teos:CHEX',
      'teos:IQ',
      'teos:BOX',
      'teos:USDT',
      'teos:VAULTA',
      'talgo:USDC-10458941',
      'talgo:USDt-180447',
      'talgo:USON-16026728',
      'talgo:SPRW-16026732',
      'talgo:KAL-16026733',
      'talgo:JPT-162085446',
      'tavaxc:link',
      'tavaxc:opm',
      'tavaxc:cop2peq',
      'tavaxc:xsgd',
      'tavaxc:bitgo',
      'tsol:srm',
      'tsol:usdc',
      'tsol:usdcv2',
      'tsol:ray',
      'tsol:gmt',
      'tsol:usdt',
      'tsol:gari',
      'tsol:orca',
      'tsol:slnd',
      'tsol:t22mint',
      'thbar:usdc',
      'thbar:txsgd',
      'tpolygon:testcopm',
      'tpolygon:opm',
      'tpolygon:usdc',
      'tpolygon:usdt',
      'tpolygon:terc18dp',
      'tpolygon:terc10dp',
      'tpolygon:terc6dp',
      'tpolygon:BitGoTest',
      'tarbeth:link',
      'tarbeth:xsgd',
      'topeth:terc18dp',
      'topeth:wct',
      'ttrx:wbtc',
      'ttrx:weth',
      'ttrx:usdc',
      'ttrx:usdt',
      'ttrx:usd1',
      'ttrx:stgusd1',
      'tsui:deep',
      'tsui:wal',
      'tbera:ibera',
      'tcoredao:stcore',
      'tworld:usdc',
      'txrp:tst-rP9jPyP5kyvFRb6ZiRghAGw5u8SGAmU4bd',
      'txrp:rlusd',
      'txrp:xat',
      'txrp:xsgd',
      'tapt:usdt',
      'tapt:nftcollection1',
      'tapt:beta3loanbook',
      'tstx:tsbtc',
      'tstx:tsip6dp',
      'tstx:tsip8dp',
      'tnear:usdc',
      'ofctusd',
      'ofctaed',
      'ofcteur',
      'ofctbtc',
      'ofctbtc4',
      'ofcteth',
      'ofchteth',
      'ofctavaxc',
      'ofctstx',
      'ofctstx:tsbtc',
      'ofctcspr',
      'ofctnear',
      'ofctltc',
      'ofctzec',
      'ofctxrp',
      'ofctxrp:rlusd',
      'ofctxrp:xsgd',
      'ofctxlm',
      'ofctdash',
      'ofctbch',
      'ofcterc',
      'ofcterc18dp13',
      'ofcterc18dp14',
      'ofcterc18dp15',
      'ofctest',
      'ofctalgo',
      'ofctetc',
      'ofcthbar',
      'ofctdoge',
      'ofctada',
      'ofctpolygon',
      'ofctbld',
      'ofcttia',
      'ofctinjective',
      'ofctosmo',
      'ofcthash',
      'ofctsei',
      'ofctzeta',
      'ofctatom',
      'ofctbsc',
      'ofctsui',
      'ofcttrx',
      'ofcttrx:usdt',
      'ofcttrx:usd1',
      'ofcttrx:stgusd1',
      'ofctdot',
      'ofctsol',
      'ofchterc18dp',
      'ofchterc6dp',
      'ofctusds',
      'ofchteth:gousd',
      'ofctgousd',
      'ofchteth:usd1',
      'ofchteth:stgusd1',
      'ofctbsc:usd1',
      'ofctbsc:stgusd1',
      'ofctarbeth',
      'ofctarbeth:link',
      'ofctcoreum',
      'ofcttao',
      'ofctcelo',
      'ofctxtz',
      'ofctavaxc:link',
      'ofctsol:gari',
      'ofctopeth',
      'ofctpolygon:link',
      'ofctpolygon:usdc',
      'ofctpolygon:usdt',
      'ofctpolygon:xsgd',
      'ofctsol:slnd',
      'ofctsol:usdt',
      'ofctsol:srm',
      'ofctsol:orca',
      'ofctsol:usdc',
      'ofctsol:ray',
      'ofctsol:gmt',
      'ofctton',
      'ofctcoredao',
      'ofctpolyx',
      'ofctbera',
      'ofctoas',
      'ofctmon',
      'ofctstt',
      'ofctworld',
      'ofctsoneium',
      'ofctflr',
      'ofctsgb',
      'ofctxdc',
      'ofctwemix',
      'ofctapt',
      'ofctbaby',
      'ofctcronos',
      'ofctinitia',
      'ofctasi',
      'ofcticp',
    ],
    gatekeep: [
      'tfiataed',
      'tfiatgbp',
      'tfiatsgd',
      'ofctgbp',
      'teth2',
      'ofctavaxc',
      'ofctbld',
      'ofcttia',
      'ofctatom',
      'ofctinjective',
      'ofctosmo',
      'ofcthash',
      'ofctsei',
      'ofctzeta',
      'ofctbsc',
      'ofctcspr',
      'ofctstx',
      'ofcttrx',
      'ofctdot',
      'ofctsui',
      'ofctpolygon',
      'ofcterc18dp13',
      'ofcterc18dp14',
      'ofcterc18dp15',
      'ofctarbeth',
      'ofctarbeth:link',
      'ofctcelo',
      'ofctxtz',
      'ofctavaxc:link',
      'ofctsol:gari',
      'ofctpolygon:link',
      'ofctpolygon:usdc',
      'ofctpolygon:usdt',
      'ofctpolygon:xsgd',
      'ofctpolyx',
      'ofctsol:slnd',
      'ofctsol:usdt',
      'ofctsol:srm',
      'ofctsol:orca',
      'ofctsol:usdc',
      'ofctsol:ray',
      'ofctsol:gmt',
      'ofctton',
      'ofcttao',
      'ofchterc18dp',
      'ofchterc6dp',
      'ofctusds',
      'ofcttrx:usdt',
      'ofctcoredao',
      'ofctgousd',
      'ofctxlm',
      'ofctbera',
      'ofctoas',
      'ofctapt',
      'ofctflr',
      'ofctsgb',
      'ofctxdc',
      'ofctwemix',
      'ofctbaby',
      'ofchteth:usd1',
      'ofctbsc:usd1',
      'tnear:tnep24dp',
      'tvet:vtho',
    ],
    bitgoOrg: {
      'BitGo Inc': {
        name: 'BitGo Inc',
        isTrust: false,
        kycRequired: false,
        kycFullyRequired: false,
        videoIdRequired: false,
        videoIdWaivedDefault: false,
        passportRequired: false,
        custodialWallet: false,
        pairedCustodialWallet: true,
        settlement: false,
        tradingAccount: false,
        trading: false,
        escrow: false,
        distributedCustodyWallet: true,
        finalCustodianApproval: false,
        travelRuleTRUST: {
          include: false,
          requireSenderInfoForReceives: false,
          restrictWhitelist: false,
        },
        userKycProperties: ['data'],
        useEntityValidationLibrary: true,
        selfCustodyLightningWallet: true,
        custodyLightningWallet: true,
        showTradingTab: true,
        staking: true,
        stakingApi: true,
        showStakingTab: true,
      },
      'BitGo Trust': {
        name: 'BitGo Trust Company',
        isTrust: true,
        kycRequired: true,
        kycFullyRequired: false,
        videoIdRequired: false,
        videoIdWaivedDefault: true,
        passportRequired: false,
        custodialWallet: true,
        pairedCustodialWallet: false,
        settlement: true,
        tradingAccount: true,
        trading: true,
        escrow: true,
        distributedCustodyWallet: false,
        finalCustodianApproval: false,
        travelRuleTRUST: {
          include: true,
          requireSenderInfoForReceives: false,
          restrictWhitelist: false,
          minimumTxAmount: 10,
        },
        userKycProperties: ['data', 'documents'],
        useEntityValidationLibrary: true,
        selfCustodyLightningWallet: true,
        custodyLightningWallet: true,
        showTradingTab: true,
        staking: true,
        stakingApi: true,
        showStakingTab: true,
      },
      'BitGo New York': {
        name: 'BitGo New York Trust Company, LLC',
        isTrust: true,
        kycRequired: true,
        kycFullyRequired: false,
        videoIdRequired: false,
        videoIdWaivedDefault: true,
        passportRequired: false,
        custodialWallet: true,
        pairedCustodialWallet: false,
        settlement: false,
        tradingAccount: true,
        trading: false,
        escrow: false,
        distributedCustodyWallet: false,
        finalCustodianApproval: false,
        travelRuleTRUST: {
          include: true,
          requireSenderInfoForReceives: false,
          restrictWhitelist: false,
          minimumTxAmount: 10,
        },
        userKycProperties: ['data', 'documents'],
        useEntityValidationLibrary: true,
        selfCustodyLightningWallet: true,
        custodyLightningWallet: true,
        showTradingTab: false,
        staking: true,
        stakingApi: true,
        showStakingTab: true,
      },
      'BitGo Germany': {
        name: 'BitGo Europe GmbH',
        isTrust: true,
        kycRequired: true,
        kycFullyRequired: true,
        videoIdRequired: false,
        videoIdWaivedDefault: false,
        passportRequired: false,
        custodialWallet: true,
        pairedCustodialWallet: false,
        settlement: false,
        tradingAccount: false,
        trading: false,
        escrow: true,
        distributedCustodyWallet: false,
        finalCustodianApproval: false,
        travelRuleTRUST: {
          include: false,
          requireSenderInfoForReceives: false,
          restrictWhitelist: false,
        },
        userKycProperties: ['data', 'documents', 'residency'],
        useEntityValidationLibrary: true,
        selfCustodyLightningWallet: true,
        custodyLightningWallet: true,
        showTradingTab: false,
        staking: true,
        stakingApi: true,
        showStakingTab: true,
      },
      'BitGo Switzerland': {
        name: 'BitGo GmbH',
        isTrust: true,
        kycRequired: true,
        kycFullyRequired: false,
        videoIdRequired: true,
        videoIdWaivedDefault: false,
        passportRequired: true,
        custodialWallet: true,
        pairedCustodialWallet: false,
        settlement: false,
        tradingAccount: true,
        trading: false,
        escrow: false,
        distributedCustodyWallet: false,
        finalCustodianApproval: false,
        travelRuleTRUST: {
          include: false,
          requireSenderInfoForReceives: false,
          restrictWhitelist: false,
        },
        userKycProperties: ['data', 'documents', 'residency', 'passport'],
        useEntityValidationLibrary: true,
        selfCustodyLightningWallet: true,
        custodyLightningWallet: true,
        showTradingTab: false,
        staking: true,
        stakingApi: true,
        showStakingTab: true,
      },
      'BitGo Europe ApS': {
        name: 'BitGo Europe ApS',
        isTrust: true,
        kycRequired: true,
        kycFullyRequired: true,
        videoIdRequired: false,
        videoIdWaivedDefault: false,
        passportRequired: false,
        custodialWallet: true,
        pairedCustodialWallet: false,
        settlement: false,
        tradingAccount: true,
        trading: false,
        escrow: true,
        distributedCustodyWallet: false,
        finalCustodianApproval: false,
        travelRuleTRUST: {
          include: true,
          requireSenderInfoForReceives: true,
          restrictWhitelist: true,
        },
        userKycProperties: ['data', 'documents', 'residency'],
        useEntityValidationLibrary: true,
        selfCustodyLightningWallet: true,
        custodyLightningWallet: true,
        showTradingTab: true,
        staking: true,
        stakingApi: true,
        showStakingTab: true,
      },
      'Frankfurt DE Trust': {
        name: 'Frankfurt Deutschland Trust',
        isTrust: true,
        kycRequired: true,
        kycFullyRequired: true,
        videoIdRequired: false,
        videoIdWaivedDefault: false,
        passportRequired: false,
        custodialWallet: true,
        pairedCustodialWallet: false,
        settlement: false,
        tradingAccount: true,
        trading: true,
        escrow: true,
        distributedCustodyWallet: false,
        finalCustodianApproval: false,
        travelRuleTRUST: {
          include: true,
          requireSenderInfoForReceives: true,
          restrictWhitelist: true,
          minimumTxAmount: 0,
        },
        userKycProperties: ['data', 'documents', 'residency'],
        useEntityValidationLibrary: true,
        selfCustodyLightningWallet: true,
        custodyLightningWallet: true,
        showTradingTab: true,
        staking: true,
        stakingApi: true,
        showStakingTab: true,
      },
      'BitGo Sister Trust 1': {
        name: 'BitGo Sister Trust 1',
        isTrust: true,
        kycRequired: true,
        kycFullyRequired: true,
        videoIdRequired: false,
        videoIdWaivedDefault: false,
        passportRequired: false,
        custodialWallet: true,
        pairedCustodialWallet: false,
        settlement: false,
        tradingAccount: false,
        trading: false,
        escrow: false,
        distributedCustodyWallet: false,
        finalCustodianApproval: false,
        travelRuleTRUST: {
          include: false,
          requireSenderInfoForReceives: false,
          restrictWhitelist: false,
        },
        userKycProperties: ['data', 'documents'],
        useEntityValidationLibrary: true,
        selfCustodyLightningWallet: true,
        custodyLightningWallet: true,
        showTradingTab: true,
        staking: true,
        stakingApi: true,
        showStakingTab: true,
      },
      'BitGo Korea': {
        name: 'BitGo Korea',
        isTrust: true,
        kycRequired: true,
        kycFullyRequired: true,
        videoIdRequired: false,
        videoIdWaivedDefault: false,
        passportRequired: false,
        custodialWallet: true,
        pairedCustodialWallet: false,
        settlement: false,
        tradingAccount: true,
        trading: false,
        escrow: false,
        distributedCustodyWallet: false,
        finalCustodianApproval: false,
        travelRuleTRUST: {
          include: false,
          requireSenderInfoForReceives: false,
          restrictWhitelist: false,
        },
        userKycProperties: ['data', 'documents'],
        useEntityValidationLibrary: true,
        selfCustodyLightningWallet: true,
        custodyLightningWallet: true,
        showTradingTab: false,
        staking: false,
        stakingApi: false,
        showStakingTab: false,
      },
      'BitGo Singapore': {
        name: 'BitGo Singapore Pte. Ltd.',
        isTrust: true,
        kycRequired: true,
        kycFullyRequired: false,
        videoIdRequired: false,
        videoIdWaivedDefault: true,
        passportRequired: false,
        custodialWallet: true,
        pairedCustodialWallet: false,
        settlement: false,
        tradingAccount: true,
        trading: true,
        escrow: false,
        distributedCustodyWallet: false,
        finalCustodianApproval: true,
        travelRuleTRUST: {
          include: true,
          requireSenderInfoForReceives: true,
          restrictWhitelist: true,
          minimumTxAmount: 10,
        },
        userKycProperties: ['data', 'documents'],
        useEntityValidationLibrary: true,
        selfCustodyLightningWallet: true,
        custodyLightningWallet: true,
        showTradingTab: true,
        staking: true,
        stakingApi: true,
        showStakingTab: true,
      },
      'BitGo Custody MENA FZE': {
        name: 'BitGo Custody MENA FZE',
        isTrust: true,
        kycRequired: true,
        kycFullyRequired: false,
        videoIdRequired: false,
        videoIdWaivedDefault: true,
        passportRequired: false,
        custodialWallet: true,
        pairedCustodialWallet: false,
        settlement: true,
        tradingAccount: true,
        trading: true,
        escrow: true,
        distributedCustodyWallet: false,
        finalCustodianApproval: false,
        travelRuleTRUST: {
          include: true,
          requireSenderInfoForReceives: false,
          restrictWhitelist: false,
          minimumTxAmount: 10,
        },
        userKycProperties: ['data', 'documents'],
        useEntityValidationLibrary: true,
        selfCustodyLightningWallet: true,
        custodyLightningWallet: true,
        showTradingTab: false,
        staking: true,
        stakingApi: true,
        showStakingTab: true,
      },
    },
    mpc: {
      bitgoPublicKey:
        '-----BEGIN PGP PUBLIC KEY BLOCK-----\r\n\r\nxk8EYqEU5hMFK4EEAAoCAwQDdbAIZrsblEXIavyg2go6p9oG0SqWTgFsdHTc\r\nBhqdIS/WjQ8pj75q+vLqFtV9hlImYGInsIWh97fsigzB2owyzRhoc20gPGhz\r\nbUB0ZXN0LmJpdGdvLmNvbT7ChAQTEwgAFQUCYqEU5wILCQIVCAIWAAIbAwIe\r\nAQAhCRCJNRsIDGunexYhBHRL5D/8nRM3opQnXok1GwgMa6d7tg8A/24A9awq\r\nSCJx7RddiUzFHcKhVvvo3R5N7bHaOGP3TP79AP0TavF2WzhUXmZSjt3IK23O\r\n7/aknbijVeq52ghbWb1SwsJ1BBATCAAGBQJioRTnACEJEAWuA35KJgtgFiEE\r\nZttLPR0KcYvjgvJCBa4DfkomC2BsrwD/Z+43zOw+WpfPHxe+ypyVog5fnOKl\r\nXwleH6zDvqUWmWkA/iaHC6ullYkSG4Mv68k6qbtgR/pms/X7rkfa0QQFJy5p\r\nzlMEYqEU5hIFK4EEAAoCAwSsLqmfonjMF3o0nZ5JHvLpmfTA1RIVDsAEoRON\r\ntZA6rAA23pGl6s3Iyt4/fX9Adzoh3EElOjMsgi8Aj3dFpuqiAwEIB8J4BBgT\r\nCAAJBQJioRTnAhsMACEJEIk1GwgMa6d7FiEEdEvkP/ydEzeilCdeiTUbCAxr\r\np3vM7AD9GPp6HhYNEh2VVCDtFSt14Bni5FVM5icpVDo6w9ibvWAA/2Ti3Jv4\r\nIhIxl81/wqAgqigIblrz6vjtagr9/ykXQCW3\r\n=skCo\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n',
      bitgoMPCv2PublicKey:
        '-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nxk8EZiF3CBMFK4EEAAoCAwQWD7Pa752fAl4z0PxfWVC05d89vfo80PyUQ3Er\nLXlhGLkik+NkAl/DBd8diN7i4kTvRoIo0xrHU+lZgdgt+ct5zRhoc20gPGhz\nbUB0ZXN0LmJpdGdvLmNvbT7ChAQTEwgANgUCZiF3CAILCQkQ5ycuezbbVOkC\nFQgCFgACGwMCHgEWIQRPr6GNiE7tRv0p4afnJy57NttU6QAAbAYA+wRvSLOa\ne0iREOx00HhYWP030GhN98BcZtehT9iTZMV8AP97Otkrtq6jby2f7PdEV7uv\nd4aikTa5BgnpKvl8yqL4ccKEBBATCAA2BQJmIXcKAgsJCRCZRBfch5MUcwIV\nCAIWAAIbAwIeARYhBAmXBS0TYEvmC/3L9JlEF9yHkxRzAABJ1wD+KyI1j9nu\nYWvDxwDB+JBGMt7mic77ajBOgaCabEZ0j1MA/2RCOiV2cOL3x1AOzosqofsh\niA1s9BpS14xAwrKJPwY+zlMEZiF3CBIFK4EEAAoCAwSgLs60kLzhHD3o1sDg\n0fQ/QHw6hgq9PQ5LvilUvuIGYDR79sPwrMuwy7wUcOQgJvwIOJHommDq5nj+\nKfgAtE6uAwEIB8KEBBgTCAA2BQJmIXcJAgsJCRDnJy57NttU6QIVCAIWAAIb\nDAIeARYhBE+voY2ITu1G/Snhp+cnLns221TpAADWmQD/bV9sBkwyYfYfJYTS\nqvTmubCesQDY5Ranv9wYvv7RiLQA/iwX6ZHwdbvQFVui0GrvV2iFaCHut1pn\nF4YCDqpUKidwzk8EZiF3CBMFK4EEAAoCAwTfm/HZxwvubP/rr2KOU88mkDL9\njcWjfQx1uFZ9mlIgMBV3++OgtkVE0eEe+lNWpwgksGOGrBWeQ3K0XRF0YlUp\nwsBKBBgTCAC8BQJmIXcJAgsJCRDnJy57NttU6QIVCAIWAAIbAgIeAYUgBBgT\nCAA2BQJmIXcJAgsJCRBrEMTq2oOYhgIVCAIWAAIbAgIeARYhBLFg1zIcwAmc\nRhGdOmsQxOrag5iGAAAxoAD/YNPhMmf3l4Qh7fprkmOjoU0CvFiiP+kcxTr9\nm9luVhUA/RvhIB4sqrAcSD7ZGVIQcEI14rdAFeok4Higz2cGf9R6FiEET6+h\njYhO7Ub9KeGn5ycuezbbVOkAAPnaAP0dYpya7EzvN5Q6RpIzqLFN9izyGt4Q\n6keZsvnVbW9qJAD9Fj7tAAMUbbstz/Kx9RY8qoIOFTuSwaeDXnJMrI9v84w=\n=uzVB\n-----END PGP PUBLIC KEY BLOCK-----\n',
      bitgoNitroPublicKey:
        '-----BEGIN PGP PUBLIC KEY BLOCK-----\r\n\r\nxk8EYqEU5hMFK4EEAAoCAwQDdbAIZrsblEXIavyg2go6p9oG0SqWTgFsdHTc\r\nBhqdIS/WjQ8pj75q+vLqFtV9hlImYGInsIWh97fsigzB2owyzRhoc20gPGhz\r\nbUB0ZXN0LmJpdGdvLmNvbT7ChAQTEwgAFQUCYqEU5wILCQIVCAIWAAIbAwIe\r\nAQAhCRCJNRsIDGunexYhBHRL5D/8nRM3opQnXok1GwgMa6d7tg8A/24A9awq\r\nSCJx7RddiUzFHcKhVvvo3R5N7bHaOGP3TP79AP0TavF2WzhUXmZSjt3IK23O\r\n7/aknbijVeq52ghbWb1SwsJ1BBATCAAGBQJioRTnACEJEAWuA35KJgtgFiEE\r\nZttLPR0KcYvjgvJCBa4DfkomC2BsrwD/Z+43zOw+WpfPHxe+ypyVog5fnOKl\r\nXwleH6zDvqUWmWkA/iaHC6ullYkSG4Mv68k6qbtgR/pms/X7rkfa0QQFJy5p\r\nzlMEYqEU5hIFK4EEAAoCAwSsLqmfonjMF3o0nZ5JHvLpmfTA1RIVDsAEoRON\r\ntZA6rAA23pGl6s3Iyt4/fX9Adzoh3EElOjMsgi8Aj3dFpuqiAwEIB8J4BBgT\r\nCAAJBQJioRTnAhsMACEJEIk1GwgMa6d7FiEEdEvkP/ydEzeilCdeiTUbCAxr\r\np3vM7AD9GPp6HhYNEh2VVCDtFSt14Bni5FVM5icpVDo6w9ibvWAA/2Ti3Jv4\r\nIhIxl81/wqAgqigIblrz6vjtagr9/ykXQCW3\r\n=skCo\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n',
      bitgoNitroMPCv2PublicKey:
        '-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nxk8EZiF3CBMFK4EEAAoCAwQWD7Pa752fAl4z0PxfWVC05d89vfo80PyUQ3Er\nLXlhGLkik+NkAl/DBd8diN7i4kTvRoIo0xrHU+lZgdgt+ct5zRhoc20gPGhz\nbUB0ZXN0LmJpdGdvLmNvbT7ChAQTEwgANgUCZiF3CAILCQkQ5ycuezbbVOkC\nFQgCFgACGwMCHgEWIQRPr6GNiE7tRv0p4afnJy57NttU6QAAbAYA+wRvSLOa\ne0iREOx00HhYWP030GhN98BcZtehT9iTZMV8AP97Otkrtq6jby2f7PdEV7uv\nd4aikTa5BgnpKvl8yqL4ccKEBBATCAA2BQJmIXcKAgsJCRCZRBfch5MUcwIV\nCAIWAAIbAwIeARYhBAmXBS0TYEvmC/3L9JlEF9yHkxRzAABJ1wD+KyI1j9nu\nYWvDxwDB+JBGMt7mic77ajBOgaCabEZ0j1MA/2RCOiV2cOL3x1AOzosqofsh\niA1s9BpS14xAwrKJPwY+zlMEZiF3CBIFK4EEAAoCAwSgLs60kLzhHD3o1sDg\n0fQ/QHw6hgq9PQ5LvilUvuIGYDR79sPwrMuwy7wUcOQgJvwIOJHommDq5nj+\nKfgAtE6uAwEIB8KEBBgTCAA2BQJmIXcJAgsJCRDnJy57NttU6QIVCAIWAAIb\nDAIeARYhBE+voY2ITu1G/Snhp+cnLns221TpAADWmQD/bV9sBkwyYfYfJYTS\nqvTmubCesQDY5Ranv9wYvv7RiLQA/iwX6ZHwdbvQFVui0GrvV2iFaCHut1pn\nF4YCDqpUKidwzk8EZiF3CBMFK4EEAAoCAwTfm/HZxwvubP/rr2KOU88mkDL9\njcWjfQx1uFZ9mlIgMBV3++OgtkVE0eEe+lNWpwgksGOGrBWeQ3K0XRF0YlUp\nwsBKBBgTCAC8BQJmIXcJAgsJCRDnJy57NttU6QIVCAIWAAIbAgIeAYUgBBgT\nCAA2BQJmIXcJAgsJCRBrEMTq2oOYhgIVCAIWAAIbAgIeARYhBLFg1zIcwAmc\nRhGdOmsQxOrag5iGAAAxoAD/YNPhMmf3l4Qh7fprkmOjoU0CvFiiP+kcxTr9\nm9luVhUA/RvhIB4sqrAcSD7ZGVIQcEI14rdAFeok4Higz2cGf9R6FiEET6+h\njYhO7Ub9KeGn5ycuezbbVOkAAPnaAP0dYpya7EzvN5Q6RpIzqLFN9izyGt4Q\n6keZsvnVbW9qJAD9Fj7tAAMUbbstz/Kx9RY8qoIOFTuSwaeDXnJMrI9v84w=\n=uzVB\n-----END PGP PUBLIC KEY BLOCK-----\n',
    },
    trustPubKey:
      '-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nxk8EZCXHRRMFK4EEAAoCAwTA0Lv61jqERerELITJlcI2faq35oT9Lk9SCBBN\ntyimXbmBND3hUX9wQqtgSs3GW18kXcFh8b/F5HnaILvvly+4zV5iYWNrdXAt\nZTMyOTVkMmYwOTI3MTEyMDAzMjk1YTMwIDxiYWNrdXAtZTMyOTVkMmYwOTI3\nMTEyMDAzMjk1YTMwQGUzMjk1ZDJmMDkyNzExMjAwMzI5NWEzMC5jb20+wowE\nEBMIAB0FAmQlx0UECwkHCAMVCAoEFgACAQIZAQIbAwIeAQAhCRD4xWq5wJpG\nMBYhBA3Y1+KuVvpmjbl+3fjFarnAmkYwsboA+wToeKcMgLs71lGWWxPPczYp\ndeGdzXaIfWHeHk0V7UNRAP4itmI6Yy/fSUBBLA6Udn4HNxFXkPVzrjhjjWM/\njyhtM85TBGQlx0USBSuBBAAKAgMEdh6yIzKJgoPq/RjGtGbyuMISFjTXBXDe\n3cU6d7tBwt8OKXwoQQ8uqmYQB75dQZ7/emyhy/uKeHizODA+w4H+vQMBCAfC\neAQYEwgACQUCZCXHRQIbDAAhCRD4xWq5wJpGMBYhBA3Y1+KuVvpmjbl+3fjF\narnAmkYwZzIBANKpfR8YRjAHXyy7f86mJMoTukNaFEKmtZwbhclzjk+dAQDU\noqui5/OWf+AnpgeFrL3mlM54KWIP6b+7Hy75qk+f9A==\n=n1q+\n-----END PGP PUBLIC KEY BLOCK-----\n',
  },
};
